dist: xenial
language: python
python:
  - "3.8"

install:
  - pip install -r requirements/ci.txt

env:
  - DJANGO_SETTINGS_MODULE=config.settings.ci
  - SECRET_KEY="tests"
  - DEBUG=True

script:
  - make test